services:
  coqui-tts:
    build: .
    container_name: coqui-tts-server
    restart: unless-stopped
    ports:
      - "5100:5100"
    volumes:
      - ./assets/models:/app/assets/models
      - ./assets/cache:/app/assets/cache
      - ./assets/voices:/app/assets/voices
    environment:
      - TTS_MODEL=tts_models/multilingual/multi-dataset/xtts_v2
      - TTS_HOME=/app/assets/models
      - DEBUG=false
      - COQUI_TOS_AGREED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      - nvidia.com/gpu=all
